name: jdk21

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  BUILD_NUMBER: 999999
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        distribution: 'temurin'
        java-version: 21
    - name: Build with Maven
      run: mvn -U -T 1C -Dmaven.javadoc.skip=true -B -V clean package
